///////////////////////////////////////////////////////////
//  ProcessData.cs
//  Implementation of the Class ProcessData
//  Generated by Enterprise Architect
//  Created on:      07-8-2023 ø¿»ƒ 3:27:07
//  Original author: ±Ë¿«º≠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace TcmsSimulator.TCMSData
{
	public class ProcessData : ITCMSBaseData
	{

		public ProcessData()
		{

		}

		~ProcessData()
		{

		}

		/// 
		/// <param name="address"></param>
		/// <param name="sequenceCounter"></param>
		public void SetData(string address, int sequenceCounter)
		{

		}

		/// 
		/// <param name="object"></param>
		public byte[] ToByte()
		{

			return null;
		}

	}//end ProcessData
}